# CI/CD configurationfile for starting a pipeline on gitlab 
# Gitlab- and Runner-Environment are build as a docker-containment
# reachable over http://localhost:80

default:
  image: "python:3.9.5"

stages:                # available stages in the defined direction
  - .pre
  - Linting
  - Building
  - Testing
  - Deployment

prepare:               # Delete the runner and virtual box directories for cleaning up and prevent failures
  stage: .pre
  tags:
    - docker
    - linux
    - ubuntu
  script:
    - rm -rf /home/gitlab-runner/builds/ && rm -rf /home/gitlab-runner/VirtualBox\ VMs/

before_script:         # install Python3, path-exportation and install tools from the requirements via pip3-package-installer
  - python3 --version                         
  - python3 - m venv $CI_BUILDS_DIR/venv
  - export PATH="$CI_BUILDS_DIR/venv/bin:$PATH"
  - pip3 install -r requirements.txt

flake8:                # test-stage for static code analysis which looks for style and syntax
  stage: Linting
  tags:
    - docker
    - linux
    - ubuntu
  script:              # rise the maximum line to 120 and ignore defined failurs
    - flake8 --max-line-length=120 --ignore=F401,E128,E902 *.py 

pylint:                # test-stage for static code analysis which looks for programm errors
  stage: Linting
  tags:
    - docker
    - linux
    - ubuntu
  allow_failure: true
  script:
    - pylint -d C0301 --ignore=F0001 *.py

build_job:             # build-stage for set-up the virtual machine and containerization
  image: docker
  tags:
    - docker
    - linux
    - ubuntu
  stage: Building
  script:
    - echo "Machine-Building..."
    - /usr/bin/ vagrant up
    - echo "succeeded..."

test-job:              # test-stage for testing the reachability with a small ping as example
  stage: Testing
  tags:
    - docker
    - linux
    - ubuntu
  script:
    - echo "Running-Testing..."
    - sleep 5
    - httping 192.168.100.100 -c2
    - echo "succeeded..."

deploy-job:              # deployment-stage for release the complete build on docker-hub (mecintyre)
  image: docker
  stage: Deployment
  tags:
    - docker
    - linux
    - ubuntu
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD
  script:
    - |
      if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
        tag=""
        echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
      fi
    - docker build -t "$CI_REGISTRY_IMAGE${tag}" .
    - echo "$CI_REGISTRY_IMAGE${tag}"
    - docker push "$CI_REGISTRY_IMAGE${tag}"
