# CI/CD configurationfile for starting a pipeline on gitlab 
# Gitlab- and Runner-Environment are build as a docker-containment
# reachable over http://localhost:80

image: "python:3.9.5"

before_script:                                   # install Python3, pathexportation and install pip3-package-installer
  - python3 --version
  - python3 - m venv $CI_BUILDS_DIR/venv
  - export PATH="$CI_BUILDS_DIR/venv/bin:$PATH"
  - pip3 install -r requirements.txt
  - if [ -d "/home/gitlab-runner/builds/" ]; then rm -Rf /home/gitlab-runner/builds/; fi  # Delete the runner dir for cleaning up and prevent failures

stages:                # available stages
  - Linting
  - Building
  - Testing

flake8:                # test-stage for code structure
  stage: Linting
  tags:
    - host
    - ubuntu
  script: 
    - flake8 --max-line-length=120 --ignore=F401,E128,E902 *.py 

pylint:                # test-stage for code-syntax
  stage: Linting
  tags:
    - host
    - ubuntu
  allow_failure: true
  script:
    - pylint -d C0301 *.py

build_job:             # build-stage for set-up the virtual machine 
  tags:
    - host
    - ubuntu
  stage: Building
  script:
    - echo "Machine-Building..."
    - make fresh
    - echo "succeeded..."

test-job:              # test-stage for testing the reachability with a small ping
  stage: Testing
  tags:
    - host
    - ubuntu
  script:
    - echo("Running-Testing...")
    - sleep 5
    - httping 192.168.100.100 -c2
    - echo "succeeded..."
