# global config
global:
  scrape_interval:     120s # By default, scrape targets every 15 seconds.
  evaluation_interval: 120s # By default, scrape targets every 15 seconds.
                            # scrape_timeout is set to the global default (10s).

  # Attached label for communicating with series and alerts
  external_labels:
      monitor: 'nginx-webserver'

# Load and evaluate rules
rule_files:
   - "/etc/prometheus/rules/*.yml"

# A scrape configuration of Prometheus
scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 120s
    static_configs:
         - targets: ['localhost:9090','cadvisor:8080','node-exporter:9100', 'nginx-exporter:9113']