server:
  http_listen_port: 0
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

client:
  url: https://92939:eyJrIjoiYnFhVGM0N0VXamhKbkMzcUh0QnJldGp0ZlpjMGVvQ2wiLCJuIjoiTG9raUxvZ3MiLCJpZCI6MX0=@logs-prod-us-central1.grafana.net/loki/api/v1/push

scrape_configs:
- job_name: system
  static_configs:
  - targets:
      - localhost
    labels:
      job: varlogs
      __path__: /var/log/*.log